[tool.poetry]
name = "link-check"
version = "0.1.0"
description = ""
authors = ["rogerogers <rogers@rogerogers.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
scrapy = "^2.11.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
